"""первая миграция

Revision ID: 1e081ce048a4
Revises: 
Create Date: 2025-03-31 13:55:13.689465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e081ce048a4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('conditions', 'condition_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False,
    #            autoincrement=True)
    # op.alter_column('triggerings', 'trigg_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False,
    #            autoincrement=True)
    # op.alter_column('users', 'user_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=False,
    #            autoincrement=True)
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', 'user_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True,
    #            autoincrement=True)
    # op.alter_column('triggerings', 'trigg_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True,
    #            autoincrement=True)
    # op.alter_column('conditions', 'condition_id',
    #            existing_type=sa.INTEGER(),
    #            nullable=True,
    #            autoincrement=True)
    pass
    # ### end Alembic commands ###
